//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GodownItems
    {
        public long sysSerial { get; set; }
        public long godownID { get; set; }
        public long itemID { get; set; }
        public long CTN { get; set; }
        public Nullable<int> Pcs { get; set; }
    
        public virtual Godowns Godowns { get; set; }
        public virtual Items Items { get; set; }
    }
}
