//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public long sysSerial { get; set; }
        public Nullable<long> POrderID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> FlatDiscount { get; set; }
        public Nullable<int> GSTPercentage { get; set; }
        public Nullable<long> GSTValue { get; set; }
        public Nullable<int> MarginPercentage { get; set; }
        public Nullable<int> MarkupPercentage { get; set; }
        public Nullable<int> NetRate { get; set; }
        public int Qty { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<long> TotalDisc { get; set; }
        public Nullable<long> DiscAfterTax { get; set; }
        public Nullable<long> TP { get; set; }
        public Nullable<long> GrossAmount { get; set; }
        public Nullable<int> DiscPercentage { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
