//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoverySlip
    {
        public long sysSerial { get; set; }
        public string Code { get; set; }
        public long DSRNumber { get; set; }
        public string CustomerName { get; set; }
        public string InvNo { get; set; }
        public long RecievedAmount { get; set; }
        public long BalancedAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual DailySales DailySales { get; set; }
    }
}
