//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetail
    {
        public long sysSerial { get; set; }
        public Nullable<long> SOrderID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<long> Total { get; set; }
        public Nullable<int> ExtraDiscount { get; set; }
        public Nullable<int> SaleTO { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public int Qty { get; set; }
        public Nullable<int> Bonus { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
