//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrder()
        {
            this.SaleOrderDetails = new HashSet<SaleOrderDetail>();
        }
    
        public long sysSerial { get; set; }
        public Nullable<long> SalesManID { get; set; }
        public Nullable<long> BookerID { get; set; }
        public Nullable<long> ClientID { get; set; }
        public string SaleAddress { get; set; }
        public string Remarks { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> TotalQtyPack { get; set; }
        public Nullable<int> TotalQtyLoose { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> TotalQtyBonus { get; set; }
        public Nullable<int> TotalDiscountPercentage { get; set; }
        public Nullable<long> TotalFlatDiscount { get; set; }
        public Nullable<long> TotalDiscount { get; set; }
        public Nullable<long> TotalGST { get; set; }
        public Nullable<long> TotalAdditionalGST { get; set; }
        public Nullable<int> TotalGrossSalePercentage { get; set; }
        public Nullable<long> TotalExclTax { get; set; }
        public Nullable<long> TotalInclTax { get; set; }
        public Nullable<long> GrandTotal { get; set; }
        public Nullable<long> SaleReturn { get; set; }
        public Nullable<int> NetValue { get; set; }
        public Nullable<long> CashBack { get; set; }
        public Nullable<bool> isPosted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Code { get; set; }
    
        public virtual OrderBooker OrderBooker { get; set; }
        public virtual Salesman Salesman { get; set; }
        public virtual SSClient SSClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; }
    }
}
