//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPEEDYSOLEntities : DbContext
    {
        public SPEEDYSOLEntities()
            : base("name=SPEEDYSOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Godown> Godowns { get; set; }
        public virtual DbSet<OrderBooker> OrderBookers { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<SaleOrder> SaleOrders { get; set; }
        public virtual DbSet<SaleOrderDetail> SaleOrderDetails { get; set; }
        public virtual DbSet<Salesman> Salesmen { get; set; }
        public virtual DbSet<SSAccount> SSAccounts { get; set; }
        public virtual DbSet<SSClient> SSClients { get; set; }
        public virtual DbSet<SSUser> SSUsers { get; set; }
        public virtual DbSet<SSUsersRole> SSUsersRoles { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<VoucherDetail> VoucherDetails { get; set; }
        public virtual DbSet<GodownItem> GodownItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
    }
}
