//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPEEDYDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSEnumValues
    {
        public int sysSerial { get; set; }
        public int EnumID { get; set; }
        public string EnumString { get; set; }
        public Nullable<int> EnumValue { get; set; }
    
        public virtual SSEnum SSEnum { get; set; }
    }
}
